2020-01-23 21:52:01,701 INFO: Microblog startup [in /home/whisllayjr/Documentos/microblog-v2/app/__init__.py:42]
2020-01-23 21:52:13,662 ERROR: Exception on /edit_profile [GET] [in /home/whisllayjr/Documentos/microblog-v2/venv/lib64/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/whisllayjr/Documentos/microblog-v2/venv/lib64/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/whisllayjr/Documentos/microblog-v2/venv/lib64/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/whisllayjr/Documentos/microblog-v2/venv/lib64/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/whisllayjr/Documentos/microblog-v2/venv/lib64/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/whisllayjr/Documentos/microblog-v2/venv/lib64/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/whisllayjr/Documentos/microblog-v2/venv/lib64/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/whisllayjr/Documentos/microblog-v2/venv/lib64/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/whisllayjr/Documentos/microblog-v2/app/routes.py", line 81, in edit_profile
    form = EditProfileForm(current_user.username)
  File "/home/whisllayjr/Documentos/microblog-v2/venv/lib64/python3.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/whisllayjr/Documentos/microblog-v2/app/forms.py", line 36, in __init__
    super(EditProfileForm, self).__init__(*args, **kwargs)
NameError: name 'args' is not defined
2020-01-23 21:52:21,997 ERROR: Exception on /edit_profile [GET] [in /home/whisllayjr/Documentos/microblog-v2/venv/lib64/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/whisllayjr/Documentos/microblog-v2/venv/lib64/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/whisllayjr/Documentos/microblog-v2/venv/lib64/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/whisllayjr/Documentos/microblog-v2/venv/lib64/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/whisllayjr/Documentos/microblog-v2/venv/lib64/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/whisllayjr/Documentos/microblog-v2/venv/lib64/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/whisllayjr/Documentos/microblog-v2/venv/lib64/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/whisllayjr/Documentos/microblog-v2/venv/lib64/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/whisllayjr/Documentos/microblog-v2/app/routes.py", line 81, in edit_profile
    form = EditProfileForm(current_user.username)
  File "/home/whisllayjr/Documentos/microblog-v2/venv/lib64/python3.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/whisllayjr/Documentos/microblog-v2/app/forms.py", line 36, in __init__
    super(EditProfileForm, self).__init__(*args, **kwargs)
NameError: name 'args' is not defined
2020-01-23 21:52:31,638 INFO: Microblog startup [in /home/whisllayjr/Documentos/microblog-v2/app/__init__.py:42]
2020-01-23 21:52:55,098 ERROR: Exception on /edit_profile [GET] [in /home/whisllayjr/Documentos/microblog-v2/venv/lib64/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/whisllayjr/Documentos/microblog-v2/venv/lib64/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/whisllayjr/Documentos/microblog-v2/venv/lib64/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/whisllayjr/Documentos/microblog-v2/venv/lib64/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/whisllayjr/Documentos/microblog-v2/venv/lib64/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/whisllayjr/Documentos/microblog-v2/venv/lib64/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/whisllayjr/Documentos/microblog-v2/venv/lib64/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/whisllayjr/Documentos/microblog-v2/venv/lib64/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/whisllayjr/Documentos/microblog-v2/app/routes.py", line 81, in edit_profile
    form = EditProfileForm(current_user.username)
  File "/home/whisllayjr/Documentos/microblog-v2/venv/lib64/python3.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/whisllayjr/Documentos/microblog-v2/app/forms.py", line 36, in __init__
    super(EditProfileForm, self).__init__(*args, **kwargs)
NameError: name 'args' is not defined
2020-01-23 21:55:56,579 INFO: Microblog startup [in /home/whisllayjr/Documentos/microblog-v2/app/__init__.py:42]
2020-01-24 11:37:01,574 INFO: Microblog startup [in /home/whisllayjr/Documentos/microblog-v2/app/__init__.py:42]
2020-01-24 11:37:15,332 INFO: Microblog startup [in /home/whisllayjr/Documentos/microblog-v2/app/__init__.py:42]
2020-01-28 11:01:50,435 INFO: Microblog startup [in /home/whisllayjr/Documentos/microblog-v2/app/__init__.py:42]
2020-01-28 11:04:19,793 INFO: Microblog startup [in /home/whisllayjr/Documentos/microblog-v2/app/__init__.py:42]
2020-01-28 11:10:21,438 INFO: Microblog startup [in /home/whisllayjr/Documentos/microblog-v2/app/__init__.py:42]
2020-01-28 14:20:52,314 INFO: Microblog startup [in /home/whisllayjr/Documentos/microblog-v2/app/__init__.py:42]
2020-01-28 14:25:43,237 INFO: Microblog startup [in /home/whisllayjr/Documentos/microblog-v2/app/__init__.py:42]
2020-01-28 15:51:27,324 INFO: Microblog startup [in /home/whisllayjr/Documentos/mymicroblog/app/__init__.py:42]
2020-01-28 15:51:52,594 INFO: Microblog startup [in /home/whisllayjr/Documentos/mymicroblog/app/__init__.py:42]
2020-01-28 15:51:55,598 ERROR: Exception on / [GET] [in /home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/whisllayjr/Documentos/mymicroblog/app/routes.py", line 19, in index
    form = PostForm()
NameError: name 'PostForm' is not defined
2020-01-28 15:53:47,945 INFO: Microblog startup [in /home/whisllayjr/Documentos/mymicroblog/app/__init__.py:42]
