2020-01-28 15:53:50,726 ERROR: Exception on / [GET] [in /home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/whisllayjr/Documentos/mymicroblog/app/routes.py", line 26, in index
    posts = current_user.follwed_posts().all()
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'User' object has no attribute 'follwed_posts'
2020-01-28 15:57:29,386 INFO: Microblog startup [in /home/whisllayjr/Documentos/mymicroblog/app/__init__.py:42]
2020-01-28 16:05:50,681 INFO: Microblog startup [in /home/whisllayjr/Documentos/mymicroblog/app/__init__.py:42]
2020-01-28 16:08:49,338 INFO: Microblog startup [in /home/whisllayjr/Documentos/mymicroblog/app/__init__.py:42]
2020-01-28 16:24:59,578 INFO: Microblog startup [in /home/whisllayjr/Documentos/mymicroblog/app/__init__.py:42]
2020-01-30 10:07:37,768 INFO: Microblog startup [in /home/whisllayjr/Documentos/mymicroblog/app/__init__.py:44]
2020-01-30 10:25:00,560 INFO: Microblog startup [in /home/whisllayjr/Documentos/mymicroblog/app/__init__.py:44]
2020-01-30 10:31:21,326 INFO: Microblog startup [in /home/whisllayjr/Documentos/mymicroblog/app/__init__.py:44]
2020-01-30 11:45:40,966 INFO: Microblog startup [in /home/whisllayjr/Documentos/mymicroblog/app/__init__.py:44]
2020-01-30 11:46:22,721 INFO: Microblog startup [in /home/whisllayjr/Documentos/mymicroblog/app/__init__.py:44]
2020-01-30 12:17:52,534 INFO: Microblog startup [in /home/whisllayjr/Documentos/mymicroblog/app/__init__.py:44]
2020-01-30 15:32:33,950 INFO: Microblog startup [in /home/whisllayjr/Documentos/mymicroblog/app/__init__.py:46]
2020-01-30 16:43:14,417 INFO: Microblog startup [in /home/whisllayjr/Documentos/mymicroblog/app/__init__.py:46]
2020-01-30 16:44:13,953 ERROR: Exception on /user/joe [GET] [in /home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/whisllayjr/Documentos/mymicroblog/app/routes.py", line 86, in user
    next_url=next_url, prev_url=prev_url)
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/jinja2/loaders.py", line 129, in load
    code = environment.compile(source, name, filename)
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/whisllayjr/Documentos/mymicroblog/app/templates/user.html", line 32, in template
    <li class="previous{% not prev_url %} disabled{% endif %}">
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'not'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2020-01-30 16:44:26,448 ERROR: Exception on /user/whisllaybastos [GET] [in /home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/whisllayjr/Documentos/mymicroblog/app/routes.py", line 86, in user
    next_url=next_url, prev_url=prev_url)
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/jinja2/loaders.py", line 129, in load
    code = environment.compile(source, name, filename)
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/whisllayjr/Documentos/mymicroblog/app/templates/user.html", line 32, in template
    <li class="previous{% not prev_url %} disabled{% endif %}">
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'not'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
