2020-01-28 15:53:50,726 ERROR: Exception on / [GET] [in /home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/whisllayjr/Documentos/mymicroblog/app/routes.py", line 26, in index
    posts = current_user.follwed_posts().all()
  File "/home/whisllayjr/Documentos/mymicroblog/venv/lib64/python3.7/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'User' object has no attribute 'follwed_posts'
2020-01-28 15:57:29,386 INFO: Microblog startup [in /home/whisllayjr/Documentos/mymicroblog/app/__init__.py:42]
2020-01-28 16:05:50,681 INFO: Microblog startup [in /home/whisllayjr/Documentos/mymicroblog/app/__init__.py:42]
2020-01-28 16:08:49,338 INFO: Microblog startup [in /home/whisllayjr/Documentos/mymicroblog/app/__init__.py:42]
